### ISSUE TITLE
hotspot member

### ISSUE THREAD

**Issue by synard1** [laksa19/mikhmonv3#10]
Salam kk,
sebelumnya saya ucapkan terima kasih karna udh mau berbagi aplikasi yang luar biasa ini :dagger: 

saya ada sedikit kendala kk, 
sebelumnya saya pakai yang sistem userman, 
jadi tiap member yg expire, tinggal tambah profile aja.

namun saya coba logic seperti itu di aplikasi mikhmon gk bisa ya kk

sya coba ganti user profile tetep terbaca expire

kira - kira prosedur nya biar bisa menggunakan sistem member seperti di userman gimana ya kk?
jadi data user tetep tersimpan tinggal di extend aja mau ke paket yg mana

terima kasih

**Comment by laksa19** [comment]
1. Agar user tidak terhapus setelah expired. Gunaka profile dengan expired mode Notice/Notice Record.
2. Untuk extend user yang sudah expired bisa dilakukan dengan cara reset. Masuk ke Mikhmon buka user yang expired kemudian klik tombol "Reset"
![2019-07-10_22-07](https://user-images.githubusercontent.com/16347475/60980811-6304f280-a35f-11e9-8c38-5e7a4e6d300f.png)

**Comment by synard1** [comment]
siap kk,
bisa ternyata :+1: 

satu lagi yg mau di tanya nih kk,
saya kan sebelumnya pakai sistem fup, script nya saya buat di on login script,

kalau di mikhmon, untuk ubah script on login di file mana ya kk??

dan sedikit saran juga, terkait masalah member ini, mungkin bisa di update di halaman fitur atau tips & trik mana tau ada rekan - rekan lain yang ingin implementasi hal yg sama
