### ISSUE TITLE
Apakah Mikhmon Bisa menggunakan Sistem FUP?

### ISSUE THREAD

**Issue by randhi99** [laksa19/mikhmonv3#15]
Halo kak,
Saya Sudah beberapa bulan menggunakan mikhmon,
Terbesit dibenak saya ingin menggunakan sistem FUP pengurangan speed.
Apakah bisa diterapkan di mikhmon?
Sebelumnya saya ingin berterima kasih karena anda telah menciptakan program yang sangat luar biasa ini. :)
Sekian kak

**Comment by laksa19** [comment]
tidak bisa boksu
