### ISSUE TITLE
hosting mikmon pd GCP

### ISSUE THREAD

**Issue by ivandisantoso** [laksa19/mikhmonv3#16]
Saya hosting pd GCP tp koq seperti looping ini y?

<img width="927" alt="image" src="https://user-images.githubusercontent.com/55465401/84098087-55734500-a9d4-11ea-9d07-e1f4e3aef606.png">

Boleh minta tolong solusi lengkapnya karena saya masih baru. Terima kasih

**Comment by laksa19** [comment]
tolong cek ini
https://github.com/laksa19/mikhmonv3/issues/7
