### ISSUE TITLE
issue openwrt stuck a.k.a muter teross

### ISSUE THREAD

**Issue by jakues** [laksa19/mikhmonv3#21]
di openwrt muter" doang ketemu masalahnya 
![Screenshot_20200902-103736](https://user-images.githubusercontent.com/34295920/91930202-69e08880-ed0a-11ea-9aeb-a50a660ad57a.png)
setelah tak ganti jadi (date) bisa
![Screenshot_20200902-104733](https://user-images.githubusercontent.com/34295920/91930207-6e0ca600-ed0a-11ea-8a3b-d035c25f5bf5.png)
![Screenshot_20200902-105348](https://user-images.githubusercontent.com/34295920/91930260-98f6fa00-ed0a-11ea-926e-fc9656d0e1ee.png)

**Comment by laksa19** [comment]
itu masalah settingan di web servernya, bukan di mikhmon
silakan cek, banyak yang berhasil https://www.youtube.com/results?search_query=mikhmon+openwrt
