### ISSUE TITLE
Where is the source code for MikhmonServer.exe

### ISSUE THREAD

**Issue by ohidurbappy** [laksa19/mikhmonv3#24]
Can you share the code for MikhmonServer.exe?

**Comment by ahmetozcelik** [comment]
There is no exe file. Mikhmon a php web project. you can download xampp for windows. later download mikhmon project and copy xampp to source directory. you can find videos and doc for how to use xampp on internet

**Comment by laksa19** [comment]
@ohidurbappy Sorry I can't, the source code has been deleted by accidentally, because I delete Windows on my VM.
