### ISSUE TITLE
Add User Profile: Enable & Disable Lock User

### ISSUE THREAD

**Issue by renomureza** [laksa19/mikhmonv3#25]
Bang ini gak salah tulis` Enable` harusnya `'Enable'` (string) kah?

https://github.com/laksa19/mikhmonv3/blob/bb834a9e2fd0181f6b16c5a7b7a0f852547525a3/hotspot/adduserprofile.php#L52

**Comment by laksa19** [comment]
iya salah, sipp, terima kasih
