### ISSUE TITLE
i want  PPPOE

### ISSUE THREAD

**Issue by paknetwork** [laksa19/mikhmonv3#31]
what about PPP in mikhmonv3 i can,t fine in this version

**Comment by laksa19** [comment]
Sorry, Mikhmon does not have that feature

**Comment by netlinktech** [comment]
i will pay for ppp features

**Comment by mikhmo** [comment]
#42

**Comment by mikhmo** [comment]
#45

**Comment by paknet** [comment]
i have full verstion

**Comment by paknet** [comment]
pppoe bypass hotspot users

**Comment by paknet** [comment]
raamsunae@gmail   contect
