### ISSUE TITLE
User with 1d/24h can't login after few second login on hotspot

### ISSUE THREAD

**Issue by hermawanherry** [laksa19/mikhmonv3#5]
User with 1d/24h can't login after few second login on hotspot

![2019-03-31_09-59-34](https://user-images.githubusercontent.com/9605972/55284213-1131f100-539c-11e9-9cc4-f99316a234b7.png)

**Comment by candraekas** [comment]
![image](https://user-images.githubusercontent.com/3499950/55287672-2d528400-53d6-11e9-9391-844539789111.png)
Saya juga mengalami hal serupa.

**Comment by laksa19** [comment]
Itu terjadi di user dengan validity 1d yang login pada taggal 31 Maret dan seharusnya expired di 1 April. Namun ada kesalahan penghitungan tanggal profile monitor di scheduler, sehingga user tereksekusi expired.

Bug itu sudah teratasi,  langkahnya sebagai berikut.

1. Silakan update Mikhmon ke versi terbaru,
2. Update user profile (buka user profile dan simpan)
3. Reboot Mikrotik

**Comment by mikhmo** [comment]
Nice

**Comment by networkpark** [comment]
Hi, I am using Mikhmon a long time. I would like to authenticate with mobile number. Is it possible to integrate that feature to Mikhmon.
