### ISSUE TITLE
Add PPPoE Server Managemen

### ISSUE THREAD

**Issue by animegasan** [laksa19/mikhmonv3#54]
English

> I want to ask, why don't we just create a PPPoE Server Management menu to manage PPPoE Clients in Mikhmon?
> 
> If there is no desire to add V3 or V4. Can I develop Mikhmon from these sources with the addition of PPPoE Server and do a Pull request?
> 
> Thank You!

Indonesia

> Saya ingin bertanya, mengapa tidak kita buat saja menu PPPoE Server Managemen untuk mengelola PPPoE Client di Mikhmon?
> 
> Jika memang tidak ada keinginan untuk ditambahkan pada V3 maupun V4. Apakah boleh saya kembangkan mikhmon dari sources ini dengan tambahan PPPoE Server dan melakukan Pull request nya?
> 
> Terima kasih!

@laksa19 

Issue: #31

**Comment by animegasan** [comment]
English

> Addition
> 
> I also want to add a package into OpenWRT with the name luci-app-mikhmon.

Indonesia

> Tambahan
> 
> Saya juga ingin menambahkan paket ke dalam OpenWRT dengan nama luci-app-mikhmon.

**Comment by robbi21** [comment]
I agree with adding PPPOE server in Mikhmon..
so you can develop luci in openwrt..

**Comment by animegasan** [comment]
@laksa19 ????

**Comment by paknet** [comment]
i have  Full version with PPPOE

**Comment by animegasan** [comment]
> i have Full version with PPPOE

it's better to be supported directly by the developer

**Comment by paknet** [comment]
but developer not responding
