### ISSUE TITLE
Request fitur untuk menghapus salah satu item dalam laporan.

### ISSUE THREAD

**Issue by candraekas** [laksa19/mikhmonv3#6]
![image](https://user-images.githubusercontent.com/3499950/55290701-9949e200-5400-11e9-9b00-f4ad201b1240.png)

Request untuk fitur menghapus salah satu item dalam laporan, karena ada contoh kasus di saya beberapa voucher yang tidak jadi digunakan / dikembalikan / koreksi penjualan.

**Comment by laksa19** [comment]
Fitur yang Anda maksud sudah ada sejak lama di Mikhmon Online, namun untuk Mikhmon Free tidak mendapatkan fitur itu.
