### ISSUE TITLE
add router 

### ISSUE THREAD

**Issue by anwer-algawe93** [laksa19/mikhmonv3#7]
![Capture](https://user-images.githubusercontent.com/20266313/56110127-9e0bab80-5f53-11e9-8052-f83207a2410c.PNG)
 when i try to add my router still like this

**Comment by laksa19** [comment]
That is a problem in the Mikhmon folder permissions, Mikhmon can't write data config.

**Comment by anwer-algawe93** [comment]
where i can find the config file !!!!!

**Comment by laksa19** [comment]
this way to solve the problems.
1.``` sudo chown -R UserWebserver:UserWebserver  /to/mikhmon/dir```
2. ```chmod -R 755  /to/mikhmon/dir```

* UserWbserver you can check from htop like this screenshot

![mikhmon-chmown-chmod](https://raw.githubusercontent.com/laksa19/laksa19.github.io/86e2cce83a7d287efabc0631eec212b660ece9b1/img/mikhmon-chown-chmod.png)
