### ISSUE TITLE
Add User Profile returned to blank page.

### ISSUE THREAD

**Issue by HakobiDev** [laksa19/mikhmonv3#8]
I got a  error from your awesome software. when I was adding a router profile for pricing and bandwidth shaping and auto delete expired voucher, it will redirected to dashboard and nothing change or added to existing user profile at MikhmonV3

**Comment by HakobiDev** [comment]
1st try
![image](https://user-images.githubusercontent.com/40719101/60184053-f74c6100-9859-11e9-8c1b-c09d6e6787ab.png)

redirected without changes
![image](https://user-images.githubusercontent.com/40719101/60184087-059a7d00-985a-11e9-93a4-831f3e7f64ff.png)

**Comment by laksa19** [comment]
Please check your Router OS version.
The minimum requirement for router os is v6.3 or above

**Comment by HakobiDev** [comment]
Ok thanks for update

my router os is v5.2

I will close this issue....

Regards,
HakobiDev
